"""
Write-back module for DataHub — Majestic's Phase 3.
Persists diagnoses generated by the agent as structuredProperties on the
entity (see config/agent_memory_property.yaml for each property's
definition) and lets a previous diagnosis be retrieved when another
entity shows the same structural pattern signature.
"""

import logging
from datetime import datetime, timezone
from typing import Any, Dict, List, Optional

from datahub.metadata.schema_classes import StructuredPropertiesClass
from datahub.specific.dataset import DatasetPatchBuilder

from src.graph.client import DataHubClient

logger = logging.getLogger(__name__)

# Must match the `id`s defined in config/agent_memory_property.yaml.
_PROP_PATTERN_SIGNATURE = "majestic.patternSignature"
_PROP_DIAGNOSIS = "majestic.diagnosis"
_PROP_BUSINESS_CONTEXT = "majestic.businessContext"
_PROP_CONFIDENCE = "majestic.confidenceScore"
_PROP_DIAGNOSED_AT = "majestic.diagnosedAt"


def _sanitize_urn_lookalikes(text: str) -> str:
    """
    Neutralizes URN-shaped substrings (`urn:li:...(...)`) inside free
    text by inserting a zero-width space after "urn:" — invisible when
    read, but breaks the DataHub UI's URN detection.

    Why this exists: `report["reason"]` (see diagnoser.py::_explain)
    always embeds the causal entity's full URN in the sentence. The
    DataHub UI tries to resolve any structured property value that
    *contains* something shaped like a URN as a reference to another
    entity (`valueEntities`), and that resolver has a real bug (confirmed
    live: it throws `IllegalArgumentException: No enum constant
    ...FabricType.$UNKNOWN`) that crashes the whole page (search, browse,
    and the dataset's own page) on any entity that has this property.
    It's not our bug, but it's our text that triggers it — so we avoid it
    here, in the only place this text gets persisted in DataHub (the
    `report["reason"]` returned via CLI/JSON is left untouched).
    """
    return text.replace("urn:li:", "urn:​li:")


class DiagnosisWriter:
    """Writes and retrieves diagnoses persisted as episodic memory in DataHub."""

    def __init__(self, client: DataHubClient):
        if not client.is_connected:
            raise RuntimeError("DataHubClient is not connected.")
        self.client = client

    def write_report(
        self,
        urn: str,
        report: Dict[str, Any],
        business_context: Optional[str] = None,
    ) -> bool:
        """
        Persists a diagnosis report in DataHub as structuredProperties.

        Args:
            urn: URN of the diagnosed dataset.
            report: Dict with the root-cause report (see MajesticAgent.diagnose).
            business_context: Optional free text. Skipped if None so it
                doesn't overwrite context a human already wrote when
                closing a previous incident with the same signature.

        Returns:
            True if the write succeeded, False otherwise.
        """
        logger.info("Writing diagnosis for %s to DataHub...", urn)

        try:
            patch = (
                DatasetPatchBuilder(urn)
                .add_structured_property(
                    _PROP_PATTERN_SIGNATURE, report["pattern_signature"]
                )
                .add_structured_property(
                    _PROP_DIAGNOSIS, _sanitize_urn_lookalikes(report["reason"])
                )
                .add_structured_property(_PROP_CONFIDENCE, float(report["confidence"]))
                .add_structured_property(
                    _PROP_DIAGNOSED_AT, datetime.now(timezone.utc).isoformat()
                )
            )
            if business_context is not None:
                patch = patch.add_structured_property(
                    _PROP_BUSINESS_CONTEXT, _sanitize_urn_lookalikes(business_context)
                )

            self.client.graph.emit_mcps(patch.build())
            logger.info("Diagnosis persisted successfully on %s", urn)
            return True
        except Exception as exc:
            logger.error("Error writing diagnosis: %s", exc)
            return False

    def find_previous_diagnosis(
        self, pattern_signature: str, exclude_urn: Optional[str] = None
    ) -> Optional[Dict[str, Any]]:
        """
        Looks for an entity already diagnosed with the same structural
        pattern signature and returns its persisted diagnosis, if any.

        Never breaks the agent's flow: if the structured search (Plan A)
        fails or finds nothing, it falls back to a free-text search (Plan
        B, see _search_by_pattern_signature). If both plans fail, returns
        None as "nothing found" instead of propagating the exception —
        not finding previous memory shouldn't stop a diagnosis.
        """
        candidate_urns = self._search_by_pattern_signature(pattern_signature)

        for candidate_urn in candidate_urns:
            if candidate_urn == exclude_urn:
                continue
            try:
                diagnosis = self.read_diagnosis(candidate_urn)
            except Exception as exc:
                logger.warning("Could not read %s, skipping it: %s", candidate_urn, exc)
                continue

            # Plan B is free text, so it can bring false positives
            # (partial matches) — confirm the exact signature before
            # accepting the reuse.
            if diagnosis and diagnosis.get("pattern_signature") == pattern_signature:
                logger.info(
                    "Signature '%s' already seen on %s, reusing diagnosis.",
                    pattern_signature,
                    candidate_urn,
                )
                return {"source_urn": candidate_urn, **diagnosis}

        return None

    def _search_by_pattern_signature(self, pattern_signature: str) -> List[str]:
        """
        Plan A: structured search via `extraFilters` over
        `structuredProperties.<qualifiedName>`. This is the correct
        mechanism, but the exact indexed field name depends on how
        DataHub maps that property in Elasticsearch — not confirmed
        against a real instance (see README, "Technical notes").

        Plan B: if Plan A throws an exception, or "works" but returns no
        results (which could be a genuine true negative, or a silently
        different search mapping), a free-text search (`query=`) is
        tried, which doesn't depend on that field name.
        """
        try:
            urns = list(
                self.client.graph.get_urns_by_filter(
                    entity_types=["dataset"],
                    extraFilters=[
                        {
                            "field": f"structuredProperties.{_PROP_PATTERN_SIGNATURE}",
                            "values": [pattern_signature],
                            "condition": "EQUAL",
                        }
                    ],
                )
            )
            if urns:
                return urns
            logger.info(
                "Plan A (structured search) found nothing for '%s'; "
                "trying Plan B (free text) in case the search field "
                "isn't the one assumed.",
                pattern_signature,
            )
        except Exception as exc:
            logger.warning(
                "Plan A (structured search) failed (%s); trying Plan B (free text).",
                exc,
            )

        try:
            return list(
                self.client.graph.get_urns_by_filter(
                    entity_types=["dataset"],
                    query=pattern_signature,
                )
            )
        except Exception as exc:
            logger.error("Plan B (free text) also failed: %s", exc)
            return []

    def read_diagnosis(self, urn: str) -> Optional[Dict[str, Any]]:
        """Reads back the persisted memory structured properties on a URN."""
        aspect = self.client.graph.get_aspect(urn, StructuredPropertiesClass)
        if not aspect or not aspect.properties:
            return None

        values = {
            assignment.propertyUrn.split(":")[-1]: assignment.values
            for assignment in aspect.properties
        }
        if _PROP_PATTERN_SIGNATURE not in values:
            return None

        def first(key, default=None):
            found = values.get(key)
            return found[0] if found else default

        return {
            "pattern_signature": first(_PROP_PATTERN_SIGNATURE),
            "reason": first(_PROP_DIAGNOSIS),
            "confidence": first(_PROP_CONFIDENCE, 0.0),
            "diagnosed_at": first(_PROP_DIAGNOSED_AT),
            "business_context": first(_PROP_BUSINESS_CONTEXT),
        }
