"""
Optional narrative synthesis of the diagnosis.

Takes a `report` already generated by MajesticAgent.diagnose() — evidence
already extracted and verified against the graph — and writes it up in
natural language for a human. This module NEVER decides what counts as
evidence and never invents links: it only writes prose about facts
RootCauseDiagnoser already extracted and verified. That separation is
what lets a real LLM be plugged in here later without risking it
hallucinating the causal chain — the LLM (if one is ever added) would
only be responsible for the phrasing, not for reasoning over the graph.

Current state: `explain()` is a deterministic template, with no calls to
any external provider (no API key, no cost, no new failure point in the
demo). The team decided not to pick a provider yet. When one is picked
(Anthropic, OpenAI, etc.), the way to plug it in
is to replace `explain()`'s body with a real call that takes the same
`report` and returns a string; the signature doesn't change, so nothing
in agent.py/main.py needs to be touched.
"""

from typing import Any, Dict, List


def explain(report: Dict[str, Any]) -> str:
    """
    Writes up MajesticAgent.diagnose()'s diagnosis in natural language.

    Args:
        report: the dict returned by MajesticAgent.diagnose() (target_urn,
            root_cause_urn, reason, causal_chain, confidence, ...).

    Returns:
        A human-readable paragraph. Never raises on its own — if the
        report has no causal chain, it explains that too.
    """
    target_urn = report.get("target_urn", "the diagnosed dataset")
    causal_chain: List[Dict[str, Any]] = report.get("causal_chain") or []

    if not causal_chain:
        return (
            f"No concrete evidence was found upstream of {target_urn}. "
            "It could be that the data is healthy, that the anomaly is "
            "beyond the configured search depth, or that the problem "
            "leaves no trace in tags, ownership, freshness, or schema — "
            "the only signals this agent knows how to read today."
        )

    steps = "\n".join(
        f"  {i}. Hop {link['hop']} ({link['urn']}): {link['evidence']}."
        for i, link in enumerate(causal_chain, start=1)
    )

    root_cause_urn = report.get("root_cause_urn")
    confidence = report.get("confidence", 0.0)

    return (
        f"The problem in {target_urn} appears to originate in {root_cause_urn}. "
        f"Evidence chain found walking the lineage backward:\n"
        f"{steps}\n"
        f"{root_cause_urn} is chosen as the root cause for being the "
        f"farthest evidenced link upstream: the farther in the lineage "
        f"with real evidence (not just the first suspect), the more "
        f"likely it is to be the origin of the problem and not a symptom "
        f"derived from it. "
        f"Heuristic confidence: {confidence * 100:.0f}% "
        f"(a reasoned ranking, not a calibrated probability — see README)."
    )
